# Form implementation generated from reading ui file 'D:\mypro\Title id reader\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import requests,os
from bs4 import BeautifulSoup

basedir = os.path.dirname(__file__)

def game_name_finder(link,titleid):
    url = f"{link}/{titleid}"
    response = requests.get(url)
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, "html.parser")
        
        h1_tag = soup.find("h1", class_="bd-title")
        
        if h1_tag:
            return h1_tag.get_text(strip=True)
        else:
            ui.txt_game_name.setPlainText(f"Title ID not found : {titleid}")
    else:
        ui.txt_game_name.setPlainText("Erorr", response.status_code)

def update_result(text):
    ui.txt_game_name.setPlainText(text)
    ui.btn_find.setDisabled(False)


def main_process(title_id: str):
    ui.btn_find.setDisabled(True)

    if len(title_id) == 9:
        title_id_up = title_id.upper()

        if "PPSA" in title_id_up:
            link = "https://prosperopatches.com"
        elif "CUSA" in title_id_up:
            link = "https://orbispatches.com"
        else:
            ui.txt_game_name.setPlainText("Title ID is Incorrect")
            ui.btn_find.setDisabled(False)
            return
    else:
        ui.txt_game_name.setPlainText("Title ID is Incorrect")
        ui.btn_find.setDisabled(False)
        return

    ui.worker = Worker(link, title_id_up)
    ui.worker.finished.connect(update_result)
    ui.worker.start()



class Worker(QtCore.QThread):
    finished = QtCore.pyqtSignal(str)

    def __init__(self, link, titleid):
        super().__init__()
        self.link = link
        self.titleid = titleid

    def run(self):
        try:
            url = f"{self.link}/{self.titleid}"
            response = requests.get(url)

            if response.status_code == 200:
                soup = BeautifulSoup(response.text, "html.parser")
                h1_tag = soup.find("h1", class_="bd-title")

                if h1_tag:
                    result = h1_tag.get_text(strip=True)
                else:
                    result = f"Title ID not found : {self.titleid}"
            else:
                result = f"Error: {response.status_code}"

        except Exception as e:
            result = f"Exception: {str(e)}"

        self.finished.emit(result)



class Ui_game_name_finder_by_title_id(object):
    def setupUi(self, game_name_finder_by_title_id):
        game_name_finder_by_title_id.setObjectName("game_name_finder_by_title_id")
#==================================================================================centralwidget
        x_1 = 493
        y_1 = 110
        game_name_finder_by_title_id.resize(x_1, y_1)
        game_name_finder_by_title_id.setMinimumSize(QtCore.QSize(x_1, y_1))
        game_name_finder_by_title_id.setMaximumSize(QtCore.QSize(x_1, y_1))
        self.centralwidget = QtWidgets.QWidget(parent=game_name_finder_by_title_id)
        self.centralwidget.setObjectName("centralwidget")
#==================================================================================le_title_id
        self.le_title_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_title_id.setGeometry(QtCore.QRect(10, 10, 171, 20))
        self.le_title_id.setObjectName("le_title_id")
        self.le_title_id.setMaxLength(9)
        self.le_title_id.setPlaceholderText("Title ID")
        self.le_title_id.returnPressed.connect(lambda: main_process(self.le_title_id.text()))
#==================================================================================btn_find
        self.btn_find = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_find.setGeometry(QtCore.QRect(190, 10, 75, 23))
        self.btn_find.setObjectName("btn_find")
        self.btn_find.clicked.connect(lambda:main_process(self.le_title_id.text()))
#==================================================================================txt_game_name
        self.txt_game_name = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.txt_game_name.setGeometry(QtCore.QRect(10, 40, 471, 41))
        self.txt_game_name.setReadOnly(True)
        self.txt_game_name.setObjectName("txt_game_name")
        self.txt_game_name.setPlaceholderText("Game Name")
#==================================================================lblSinajet
        self.lblSinajet = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(7)
        font.setItalic(True)
        self.lblSinajet.setFont(font)
        self.lblSinajet.setObjectName("lblSinajet")
        self.lblSinajet.setText("Sinajet")
#==================================================================================menubar
        game_name_finder_by_title_id.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=game_name_finder_by_title_id)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 21))
        self.menubar.setObjectName("menubar")
#==================================================================================statusbar
        game_name_finder_by_title_id.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=game_name_finder_by_title_id)
        self.statusbar.showMessage("", 0) 
        self.statusbar.addPermanentWidget(self.lblSinajet)
        self.statusbar.setObjectName("statusbar")
#==================================================================================
        game_name_finder_by_title_id.setStatusBar(self.statusbar)

        self.retranslateUi(game_name_finder_by_title_id)
        QtCore.QMetaObject.connectSlotsByName(game_name_finder_by_title_id)

    def retranslateUi(self, game_name_finder_by_title_id):
        _translate = QtCore.QCoreApplication.translate
        game_name_finder_by_title_id.setWindowTitle(_translate("game_name_finder_by_title_id", "Find Game by Title ID"))
        self.btn_find.setText(_translate("game_name_finder_by_title_id", "Find"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    game_name_finder_by_title_id = QtWidgets.QMainWindow()
    app.setWindowIcon(QtGui.QIcon(os.path.join(basedir,'icon.ico')))
    ui = Ui_game_name_finder_by_title_id()
    ui.setupUi(game_name_finder_by_title_id)
    game_name_finder_by_title_id.show()
    sys.exit(app.exec())
